### PR TITLE
TRL 42 - Study materials dialog

### PR DESCRIPTION
**Pull request by yanivel**
- Clicking on bottom bar menu Item opens Study materials dialog
- Refactor the main dialog header into its own widget
- Adds a Loader widget that loads a result and shows a loading indicator (used in Questions dialog & Study materials).

### CODE REVIEW

**Comment by igala** [comment]
looks great, few comments:
1. Menu should show 3 instead of 2
2. Clicking on back button does not close the study material
3. I would add the study material also in the settings window so friends can access the material without going inside a room.
4. iOS looks good

**Comment by yanivel** [comment]
1. Done - shows 3 under menu
2. I can't reproduce, does it also happen for the questions dialog? Could you try again with the new commits?
3. Added to settings screen as an action on the AppBar

**Comment by igala** [comment]
Back button of the Android device (not the back button you added)

**Comment by yanivel** [comment]
> Back button of the Android device (not the back button you added)

Works for me on the simulator for both buttons (button widget & Android back button) from both Settings & Dashboard screens. 
Could you give me more details so I can try and reproduce?

**Comment by igala** [comment]
could not recreate this issue with the back of the android button

**Pull request merged**
