### PR TITLE
Trl 85

### PR DESCRIPTION
**Pull request by yanivel**
Do not merge this is for general preview

### CODE REVIEW

**Comment by igala** [comment]
1. Exception on creating first time the list when parsing cammute which is not set but only after update from mqtt
2. Camera mute change does not update the ui
3. I would open the dialog not covering the screen , show the bottom bar and the top bar at least , I would consider even showing part of the room and stream

**Comment by yanivel** [comment]
1 + 2: will take care of this
3: what is the purpose of the friends screen? Why users would open it? Why would they stay there?
If this is just a different view of the friends in the video room, I would add an option to be able to change the grid to list inside the room rather than going through the menu.

**Comment by yanivel** [comment]
1+2: Done

**Comment by igala** [comment]
Number 3 has exactly the same purpose of participants in zoom,

You want see who is in the room and it’s status since you can not see all of the users at the same page.

It is should be a sort of a glimpse so it should not cover all the screen and keep the user in the feeling that he is still in the room

**Comment by igala** [comment]
Another option is to slide this dialing in animation from bottom up as fine in zoom to give a feeling that it is a dialogue that covers the dashboard

**Pull request merged**
